## Implementation of SVD

Singular-Value decomposition is the also one of the popular dimensionaloty reduction techniques and is also written as SVD.
It is the matrix- factorization method of linear algebra, and it is widelt used in different applications such as feature selection, visualization, noise reduction, and many more

In [4]:
!pip install numpy

In [23]:
import numpy as np
from numpy.linalg import eigh, norm

In [25]:
# Sample data
A = np.array([[-5, 2, 3],
              [2, 5, 1],
              [3, 1, -5]])

## Computational of matrix transpose and matrix multiplication
In Numpy, $ A^{T}A $ defines the matrix multiplication of the transpose of $A$ with $A$ which can be computed using the @ operator or to simplify things np.dot can also be used.
Here is the breakdown of the above sample data.
The given matrix above is $(3 X 3)$ matrix, transposing it doesn't change the order of the matrix.


**Multiply $A^{T}$ by $A$:** This is done by simply performing matrix multiplication, which involves taking dot product of the rows of $A^{T}$ with the columns of $A$.
The final result behind the codes is illustrated below:
$$
A^{T} @ A =
\left[
\begin{matrix}
(-5.-5 + 2.2 + 3.3) & (-5.2 + 2.5 + 3.1) & (-5.3 + 2.1 + 3.-5)\\
(2.-5 + 5.2 + 1.3) & (2.2 + 5.5 + 1.1) & (2.3 + 5.1 + 1.-5)\\
(3.-5 + 1.2 + -5.3) & (3.2 + 1.5 + -5.1) & (3.3 + 1.1 + -5.-5)
\end{matrix}
\right]$$


In [45]:
A.T@A

array([[ 38,   3, -28],
       [  3,  30,   6],
       [-28,   6,  35]])

## Finding Eigenvalues and Eigenvectors
To find the eigenvalues and eigenvectors of $A^{T}$, we need to solve the equation:
                             $A^{T} A v = λ v$
This can also be represented as:
                             $(A^{T} A - λI) v = 0  $
                             
Let's us take a look at Numerical solution:

**1. Construct of the matrix $A^{T}$.**

**2. Solve the characteristic equation $ det(A^{T} A - λI) = 0 $ to find the eigenvalues λ.**

**3. Find the eigenvectors by substituting the eigenvalues into the equation $A^{T} Av = λv.**

**Simple walkthrough example:**
From the above matrix data after $A.T@A$ has been performed the result obtained is:
          $$
A^{T} A =
\left(
\begin{matrix}
38 & 3 & -28\\
3 & 30 & 6\\
-28 & 6 & 35
\end{matrix}
\right)$$
We need to solve for the eigenvalues **λ** and eigenvectors **v** of this matrix.
The equation is given by        $det(A^{T} A - λI) = 0 $
we get 

$$
\begin{bmatrix}
38 & 3 & -28 \\ 
3 & 30 & 6 \\
-28 & 6 & 35
\end{bmatrix}
-\lambda
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
=
\begin{bmatrix}
0
\end{bmatrix}
$$


this becomes:
$$
\begin{bmatrix}
38 - \lambda & 3 & -28 \\
3 & 30 - \lambda & 6 \\
-28 & 6 & 35 - \lambda
\end{bmatrix}
= 0
$$

**Solve for λ**

This determinant leads to a cubic equation in **λ**, and solving it gives the eigenvalues.

**Find the eigenvectors**
After the eigenvalues are obtained, substitute each one into $A^{T} Av = λv$ to find the corresponding eigenvectors

In [51]:
# Getting eigenvalues and eigenvectors
eigh(A.T@A)

EighResult(eigenvalues=array([ 6.68769919, 31.66001395, 64.65228686]), eigenvectors=array([[-0.65658382,  0.22455403, -0.72005082],
       [ 0.26613407,  0.96222538,  0.05740187],
       [-0.70574099,  0.15394091,  0.69154309]]))

In [79]:
# Assigning eigenvalues and eigenvectors
ev, V = eigh(A.T@A)

In [87]:
V

array([[-0.65658382,  0.22455403, -0.72005082],
       [ 0.26613407,  0.96222538,  0.05740187],
       [-0.70574099,  0.15394091,  0.69154309]])

In [83]:
V[0]

array([-0.65658382,  0.22455403, -0.72005082])

In [89]:
V[:,0]

array([-0.65658382,  0.26613407, -0.70574099])

## Mathematical breakdown of matrix-vector multiplication and normalization steps

$A @ V[:,i] $ represents the multiplication of matrix A with the i^{th} column of matrix **V**
$A @ V[:,0] $ represents the multiplication of matrix A with the first column of matrix **V**
Similarly, 
$A @ V[:,1] and A @ V[:,2]$ represents the muliplication of matrix A with second and third column matrix

**Normalization**
- After performing the matrix-vector multiplication, the result is a new vector, but it may not be a unit vector( not having a magnitude of 1).
- The normalization step ensures that each vector $\mathbf{u}_0$, $\mathbf{u}_1$, and $\mathbf{u}_2$ has a unit length. This is done by dividing the vector by its norm(magnitude).

  The vector normalization is given by equation:
   $$|\mathbf{v}| = \sqrt{v_1^2 + v_2^2 + \ldots + v_n^2}$$
  where each normalization is resultant vector done by dividing each element of the vector by its norm
  i.e
  $$u_0 = \frac{A \cdot V_1}{|A \cdot V_1|}$$

**The main reason to normalize is to ensure that all are unit vectors i.e their magnitude is 1. This can be useful in many application like Principal Component analysis(PCA), Singular value Decomposition(SVD) and many more.**

In [91]:
u0 = A@V[:,0]/norm(A@V[:,0])
u1 = A@V[:,1]/norm(A@V[:,1])
u2 = A@V[:,2]/norm(A@V[:,2])

In [93]:
#Creating a matrix by arranging vectors u0,u1,u2 as rows and Transposing it
U = np.array([u0,u1,u2]).T

## Breakdown of experession U.T@A@V
 The operation $U.T@A@V$ performs a sequence of two matrix multiplicatiom. The first multiplies the transpose of **U** with **A**, and the second multiplies the result with **V**.

In [98]:
np.round(U.T@A@V, decimals = 5)

array([[ 2.58606, -0.     ,  0.     ],
       [-0.     ,  5.62672,  0.     ],
       [-0.     ,  0.     ,  8.04066]])

In [100]:
U

array([[ 0.65658382,  0.22455403,  0.72005082],
       [-0.26613407,  0.96222538, -0.05740187],
       [ 0.70574099,  0.15394091, -0.69154309]])

In [ ]:
# A = U@D@V.T is the SVD